// frontend/src/App.svelte
<script lang="ts">

    import { Router, Route } from "svelte-routing";
    import Login from "./lib/pages/Login.svelte";
    import Register from "./lib/pages/Register.svelte";
    import Dashboard from "./lib/pages/Dashboard.svelte";


</script>



<Router>
    <Route path="/login"><Login/></Route>
    <Route path="/registration"><Register/></Route>
    <Route path="/dashboard/*"><Dashboard/></Route>
</Router>

// frontend/src/App.tsx
import {BrowserRouter, Routes, Route } from "react-router-dom"
import './App.css'
import Index from "./pages/Index"
import Profile from "./pages/Profile"
import Registration from "./pages/Registration"

function App() {


    return (
        <BrowserRouter>
            <Routes>
                <Route path="/" Component={Index} />
                <Route path="/register" Component={Registration}/>
                <Route path="/profile" Component={Profile} />
            </Routes>
        </BrowserRouter>
  )
}

export default App
