// frontend/src/modules/auth-module/components/LoginForm.tsx
﻿import { Form, Input, Button, notification, Spin } from "antd"
import { useEffect, useState } from "react"
import { useNavigate } from "react-router"
import { Link } from "react-router-dom"
import { useStores } from "../../../hooks/RootContext"
import UserLoginDTO from "../../../models/Auth/UserLoginDTO"

export default function LoginForm() {

    const { authStore } = useStores()
    const navigate = useNavigate()
    const [isLoading, setLoading] = useState(false)
    const [api, contextHolder] = notification.useNotification()
    const [fullscreenLoading, setfsLoading] = useState(false)
    function OnFinished(values: UserLoginDTO) {

        setLoading(true)

        authStore.Login(values)
            .then(() => {
                navigate("/dashboard/profile")
            })
            .catch((error) => {
                api.error({
                    message: "Что то пошло не так",
                    placement: 'top'
                })
            })
            .finally(() => {
                setLoading(false)
            })
    }

    useEffect(() => {

        setfsLoading(true)

        if (authStore.checkAuth()) {

            setfsLoading(false)

            navigate('/dashboard/profile')
        }

        setfsLoading(false)

    }, [])


    if (fullscreenLoading) {
        return <Spin spinning={true} fullscreen/>
    }


    return (
        <>
            {contextHolder}
            <Form
                scrollToFirstError
                onFinish={OnFinished}
                colon={false}
                style={{
                    maxWidth: 800,
                }}
                wrapperCol={{ offset: 5 }}
                labelCol={{ offset: 5 }}
                labelWrap={false}

            >
                <Form.Item<UserLoginDTO>
                    label="Имя пользователя"
                    name="username"
                    rules={[
                        {
                            required: true,
                            message: "Поле является обязательным"
                        }
                    ]}
                >
                    <Input showCount placeholder="Имя пользователя" maxLength={50} />
                </Form.Item>

                <Form.Item<UserLoginDTO>
                    label="Пароль"
                    name="password"
                    rules={[
                        {
                            required: true,
                            message: "Поле является обязательным"
                        }
                    ]}
                >
                    <Input.Password placeholder="Пароль" />
                </Form.Item>

                <Form.Item
                >
                    <Button type="primary" htmlType="submit" loading={isLoading}>Войти</Button>
                </Form.Item>
                <Form.Item>
                    <Link to="/register">
                        <Button type="primary">
                            Перейти к регистрации
                        </Button>
                    </Link>
                </Form.Item>
            </Form>

        </>
    )
}

// frontend/src/lib/components/LoginForm.svelte
<script lang="ts">
    import { Form, FormGroup, Input, Button, Alert} from "@sveltestrap/sveltestrap";
    import { AuthService } from "../services/AuthService";
    import { navigate, Link } from "svelte-routing"

    let user: IUser = {
        userName:"",
        password:""
    }

    const {Login} = AuthService()

    let validated = false
    let notificationOpened = false

    const handleAuthorization = async(event: SubmitEvent) =>{
        event.preventDefault()

        try{
            const responce: Response = await Login(user)
            
            if (responce.status == 200){

                responce.json().then((data) => {

                    const {refreshToken, accessToken}: ITokens = data as ITokens
                    localStorage.setItem('accessToken', accessToken)
                    localStorage.setItem('refreshToken', refreshToken)
                })

                navigate('/dashboard/profile')
            }
            else{
                throw new Error()
            }
        }
        catch{
            notificationOpened = true
            setTimeout(()=>{
                notificationOpened = false
            }, 1000)
        }
    }
</script>

<Form {validated} on:submit={handleAuthorization}>
    <FormGroup floating label="Имя пользователя">
        <Input 
            type="text"
            placeholder = "Введите имя пользователя"
            bind:value={user.userName}
            required
        />
    </FormGroup>

    <FormGroup floating label="Пароль">
        <Input 
            placeholder = "Введите пароль" 
            type="password" 
            required
            bind:value={user.password}
        />
    </FormGroup>

    <Button type="submit" color="primary" on:click={() => validated = true}>
        Войти
    </Button>

    <Button type="button" on:click={() => navigate('/registration')}>
        Перейти к регистрации
    </Button>
</Form>
    
<Alert isOpen={notificationOpened} dismissible fade color='primary'>Что то пошло не так!</Alert>
